// Generated by Supernova, do not modify
import Foundation

/// The PrismIconSource is a singleton that holds the current ``PrismIconProvider``. The current provider serves as the source for all icons definitions.
///
/// To activate a new icon theme please use the provided activators.
///
/// ```swift
/// PrismDefaultIconActivator.activate*()
/// ```
///
/// Each theme package includes an associated activator. For client development, there should be no need to interact with this class unless you wish to observe the current theme.
public class PrismIconSource: ObservableObject {

    /// The current icon theme provider
    @Published public var theme: PrismIconProvider = PrismDefaultIconProvider()

    /// The shared instance of the PrismIconSource
    public static let shared = PrismIconSource()

    private init() {}

    /// Activates the provided theme.
    ///
    /// This function is publicly exposed so that other icon packages can use it to activate their themes through their own activators. Clients should avoid calling this directly and instead use the provided activators.
    ///
    /// - Parameter theme: The icon provider to be set as the new icon source.
    public static func activate(theme: PrismIconProvider) {
        shared.theme = theme
    }
}
