// Generated by Supernova, do not modify
import SwiftUI
import UIKit

/// Defines the icon provider for a particular theme
public protocol PrismIconProvider {

    /// The bundle containing the icons for the theme
    var iconBundle: Bundle { get }

    /// The name of the theme
    var name: String { get }
}
